appfive/urls.py
from django.urls import path
from . import views

#Template name
app_name = "appfive"

urlpatterns = [
    path('register/',views.register , name="register"),
    path("login/",views.user_login,name="login"),
    path("logout/",views.user_logout,name="logout"),
    path("special/",views.special_page,name="special")
]

fift_project/urls.py
from django.contrib import admin
from django.urls import path,include
from appfive import views
urlpatterns = [
    path('', views.index ,name="index"),
    path('admin/', admin.site.urls),
    path('appfive/', include('appfive.urls'))
]

appfive/models.py
from django.db import models
from django.contrib.auth.models import User
# User class already has email username password first name last name 
# Hence you just extend the functionality by adding a onetoonefield with the new model class
# Create your models here.

class UserProfileAndPortfolioInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    github_page = models.URLField(blank=True)
    profile_picture = models.ImageField(upload_to="profile_pictures", blank=True)

    def __str__(self):
        return self.user.username

appfive/forms.py
from django import forms
from django.contrib.auth.models import User
from appfive.models import UserProfileAndPortfolioInfo
#Verify two things 
#1. delete line 7 and see
#2. replace line 16 as '__all__'
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileAndPortfolioForm(forms.ModelForm):
    class Meta():
        model = UserProfileAndPortfolioInfo
        fields = ('github_page','profile_picture')

appfive/views.py
from django.shortcuts import render
from . import forms
from django.http import HttpResponseRedirect , HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,"appfive/index.html")

def register(request):
    user_registered = False

    if request.method == "POST":
        user_form = forms.UserForm(request.POST)
        profile_form = forms.UserProfileAndPortfolioForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_picture' in request.FILES:
                profile.profile_picture = request.FILES['profile_picture']
            profile.save()

            user_registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = forms.UserForm()
        profile_form = forms.UserProfileAndPortfolioForm()

    return render(request,'appfive/register.html',
                          {
                              'user_registered':user_registered,
                              'user_form':user_form,
                              'profile_form':profile_form
                           })

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            
            else:
                return HttpResponse("Account is not active .. Please try with some other user ")
        else:
            print("Incorrect password recognised .. \n Username {} \n Password {} ".format(username,password))
            return HttpResponse("Incorrect Details Please try again !")
    
    else:
        return render(request,'appfive/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special_page(request):
    return HttpResponse("Logged in ... Check !!")

templates/appfive/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Django Level Five</title>
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'index' %}">Django</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'appfive:register' %}">Register</a>
                </li>  
                {% if user.is_authenticated %}
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'appfive:logout' %}">Logout</a>
                    </li> 
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'appfive:login' %}">Login</a>
                    </li> 
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'appfive:special' %}">Special Link</a>
                </li> 
            </ul>
        </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>  
</body>
</html>

templates/appfive/index.html
{% extends 'appfive/basic.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>DJANGO LEVEL FIVE</h1>
    <h3>Click on register for new users or Login for existing users</h3>
</div>
{% endblock %}

templates/appfive/login.html
{% extends 'appfive/basic.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Login page</h1>
    <h3>Please fill out the details to login</h3>
    <form action= "{% url 'appfive:login' %} " method="POST">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" id="username">

        <label for="password">Password</label>
        <input type="password" name="password" id="password">

        <input type="submit" value="Login">
    </form>
</div>
{% endblock %}

templates/appfive/register.html
{% extends 'appfive/basic.html' %}
{% block body_block %}
    <div class="jumbotron">
        {% if user_registered %}
            <h1>Thank you for regitering please proceed to the login page</h1>
        {% else %}
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" value="submit">
            </form>
        {% endif %}
    </div> 
{% endblock %}